version: "2"
services:
  web1:
    build: .
    ports:
      - "8081:8080"
    links:
      - mongo
  web2:
    build: .
    ports:
      - "8082:8080"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
  nginx:
        build: ./nginx
        container_name: ms_nginx
        links:
            - web1
            - web2
        ports:
            - "8080:80"